#!/bin/bash
# Quick Reference Card for ExplainGrade Vercel Deployment

echo "═══════════════════════════════════════════════════════"
echo "  📋 ExplainGrade Quick Reference Card"
echo "═══════════════════════════════════════════════════════"
echo ""

echo "🚀 QUICK START (Pick ONE):"
echo "─────────────────────────────────────────────────────"
echo ""
echo "1️⃣ Python HTTP Server (Simplest):"
echo "   python -m http.server 8000"
echo "   → Open: http://localhost:8000"
echo ""
echo "2️⃣ Node.js Server (Simulates Vercel - RECOMMENDED):"
echo "   npm install"
echo "   npm start"
echo "   → Open: http://localhost:3000"
echo ""
echo "3️⃣ Via npx serve:"
echo "   serve ."
echo "   → Open: http://localhost:3000"
echo ""

echo "═══════════════════════════════════════════════════════"
echo "  🔍 TESTING CHECKLIST"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "✅ Verify These Work Locally:"
echo "   [ ] Page loads (no blank/white screen)"
echo "   [ ] CSS styled correctly (not plain text)"
echo "   [ ] Dark/light theme toggle works"
echo "   [ ] All links navigate"
echo "   [ ] File uploads work"
echo "   [ ] No console errors (F12)"
echo ""

echo "═══════════════════════════════════════════════════════"
echo "  📤 DEPLOY TO VERCEL"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Option A: Web Dashboard (Easiest)"
echo "─────────────────────────────────────────────────────"
echo "1. Push to GitHub:"
echo "   git add ."
echo "   git commit -m 'Ready for Vercel'"
echo "   git push origin main"
echo ""
echo "2. Go to: https://vercel.com/dashboard"
echo "3. Click: Add New → Project"
echo "4. Select: Your GitHub Repo"
echo "5. Framework: 'Other'"
echo "6. Click: Deploy"
echo ""
echo "Option B: Vercel CLI"
echo "─────────────────────────────────────────────────────"
echo "vercel --prod"
echo ""

echo "═══════════════════════════════════════════════════════"
echo "  🐛 TROUBLESHOOTING"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "Local works but Vercel fails?"
echo "─────────────────────────────────────────────────────"
echo "1. Check file paths are relative (no leading /)"
echo "2. Check filenames match case (app.js not app.JS)"
echo "3. Check npm install ran: ls -la node_modules/"
echo "4. View Vercel build logs: vercel.com/dashboard"
echo ""
echo "What's the error? Check in:"
echo "─────────────────────────────────────────────────────"
echo "1. Browser Console (F12) for JavaScript errors"
echo "2. Network Tab (F12) for failed file loads"
echo "3. Vercel Build Logs for deployment errors"
echo ""

echo "═══════════════════════════════════════════════════════"
echo "  📚 DETAILED GUIDES"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "📖 Read these files in order:"
echo "   1. LOCAL_TESTING_GUIDE.md       (Test your site)"
echo "   2. VERCEL_DEPLOYMENT_GUIDE.md   (Deploy steps)"
echo "   3. VERCEL_ISSUES_FIXES.md       (Fix errors)"
echo ""

echo "═══════════════════════════════════════════════════════"
echo "  ⚡ MOST COMMON ISSUES"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "❌ \"Cannot GET /\""
echo "   ✅ Solution: Ensure index.html in root directory"
echo ""
echo "❌ No CSS (page unstyled)"
echo "   ✅ Solution: Check link href=\"style.css\" in HTML"
echo ""
echo "❌ Script not loading"
echo "   ✅ Solution: Use relative paths (src=\"app.js\")"
echo ""
echo "❌ Libraries undefined (Papa, XLSX)"
echo "   ✅ Solution: CDN scripts must load BEFORE local scripts"
echo ""
echo "❌ Works locally but not on Vercel"
echo "   ✅ Solution: Check npm install ran"
echo "   ✅ Solution: Check for case-sensitive filenames"
echo ""

echo "═══════════════════════════════════════════════════════"
echo "  🎯 NEXT STEPS"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "1. Test locally (pick one method above)"
echo "2. Verify all checks pass"
echo "3. Deploy to Vercel (Option A or B)"
echo "4. Check if live site works"
echo "5. If issues, refer to VERCEL_ISSUES_FIXES.md"
echo ""
echo "═══════════════════════════════════════════════════════"
echo ""
